<#
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
#>

$Fibonacci = @(1,1)
while ($Fibonacci[-1] -lt 4000000){
    $Fibonacci += $Fibonacci[-1] + $Fibonacci[-2]
}

$Fibonacci | Where-Object {$_ % 2 -eq 0} | Measure-Object -Sum | Select-Object -ExpandProperty Sum